// options
let socket = Socket(domain: .AF_SP, proto: .PULL)

assert(socket.linger == 1000)
assert(socket.sndbuf == 131072)
assert(socket.rcvbuf == 131072)
assert(socket.rcvmaxsize == 1048576)
assert(socket.sndtimeo == -1)
assert(socket.rcvtimeo == -1)
assert(socket.reconnect_ivl == 100)
assert(socket.reconnect_ivl_max == 0)
assert(socket.sndprio == 8)
assert(socket.rcvprio == 8)
assert(socket.ipv4only == 1)
assert(socket.name == "0")
